### ISSUE TITLE
Add threadId to PatternLayout

### ISSUE THREAD

**Issue by rob93c** [qos-ch/logback#710]
Given the project already supports printing the current thread name, it should also be able to retrieve the `threadId`.

This would be useful when dealing with virtual threads, I noticed that ones created via [`Executors.newVirtualThreadPerTaskExecutor()`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/Executors.html#newVirtualThreadPerTaskExecutor()) don't have a name and they would be shown as an empty string:

![image](https://github.com/qos-ch/logback/assets/1816483/88c0e2fc-a2b5-433f-9d4d-51908125b55f)

**Comment by danishnawab** [comment]
Unlike platform threads, virtual threads do not return a name unless explicitly set. From the [javadoc](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html):

>Virtual threads do not have a thread name by default. The [getName](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html#getName()) method returns the empty string if a thread name is not set.

Given that libraries and frameworks (e.g. Spring) create virtual threads but don't explicitly set a name, the logs don't contain any thread name which affects the troubleshooting experience.
The ability to include `threadId`s in logback log messages would help deal with this problem.

Another solution could perhaps be to synthesize a thread name, something like:
```java
public String getThreadName() {
    if (this.threadName == null) {
        final Thread currentThread = Thread.currentThread();
        if (currentThread.getName() != null) {
            this.threadName = currentThread.getName();
        } else if (currentThread.isVirtual()) { // replace with the reflective call when building with older JDKs
            this.threadName = "virtual-thread-" + currentThread.threadId();
        } else {
            this.threadName = "unnamed-" + currentThread.threadId();
        }
    }

    return this.threadName;
}
```

@ceki any thoughts on this?

**Comment by ceki** [comment]
@danishnawab  Thank you for the proposal. See commit 5a3613346573

**Comment by danishnawab** [comment]
That's amazing @ceki, thank you!

**Comment by getaceres** [comment]
It seems that the build failed for some (apparently) temporary errors. Could this be retried? It would be very useful to have this now that Spring Boot has support for virtual threads.

**Comment by mkurz** [comment]
This is part of 1.5 now. I think this can be closed?

**Comment by davidalayachew** [comment]
This feature would be valuable for me.

I know the comment thread talked about Virtual Threads, but this is valuable for Platform Threads too. Thread ID is a concise way to disambiguate multiple, concurrent processes. Compare that to Thread Name, which is also unique, but it can also be unexpectedly long/large.

@ceki your thoughts?
