### ISSUE TITLE
class org.apache.logging.slf4j.Log4jLogger cannot be cast to class ch.qos.logback.classic.Logger

### ISSUE THREAD

**Issue by notxndy** [qos-ch/logback#723]
This bug(?) appears in later versions of ch.qos.logback: classic > 1.2.12

I am using the below code in a unit test class with the following imports and declarations

`
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import org.slf4j.LoggerFactory;

private final Logger logger = (Logger) LoggerFactory.getLogger(MyClass.class);
    private final ListAppender<ILoggingEvent> listAppender = new ListAppender<>();

    @BeforeEach
    public void setUp() {
        listAppender.start();
        logger.addAppender(listAppender);
  }
`

I am using org.slf4j:api version 2.0.9 and logback-classic version 1.2.12 as that's the last version that doesn't break the casting.

Hoping I can get an answer or a guide to this issue.

**Comment by ceki** [comment]
SLF4J 2.x requires logback 1.3 or later.

**Comment by notxndy** [comment]
Right but 1.3 and above breaks the casting.

**Comment by ceki** [comment]
It should not. What is the exception?

**Comment by notxndy** [comment]
As the title reads: `java.lang.ClassCastException: class org.apache.logging.slf4j.Log4jLogger cannot be cast to class ch.qos.logback.classic.Logger`

**Comment by notxndy** [comment]
I see such a jar is compiled under the following dependency 

`[INFO] \- org.springframework.boot:spring-boot-starter-log4j2:jar:2.7.11:compile
[INFO]    +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.18.0:compile`

Will exclude it and post results.

**Comment by notxndy** [comment]
For some reason I wasn't able to exclude from the dependency tree. But I'm sure this is still an acceptable answer.

**Comment by ceki** [comment]
https://github.com/qos-ch/slf4j/issues/415#issuecomment-2061741015 might be related.
