### ISSUE TITLE
JsonEncoder message is not interpolated

### ISSUE THREAD

**Issue by madisp** [qos-ch/logback#731]
Invoking `log.info("Destroyed {} gracefully in {} ms.", process, duration)` doesn't interpolate the values in the `message` field when using `JsonEncoder`.

The arguments are there in the `arguments` array so technically interpolation can be done downstream (e.g. the consumer of the ndjson-formatted output) but this is a bit surprising and makes integration with log sinks harder.

Any plans to have some form of interpolation supported here? I'd be happy to provide a PR.

**Comment by res1st** [comment]
In the old version control there was a similar report.
https://jira.qos.ch/browse/LOGBACK-1748?jql=text%20~%20%22jsonencoder%22

I was also surprised today that my Loki logs shows the {} in the log messages when I use the JsonEncoder instead of the logstash encoder from the past.

**Comment by lbueker** [comment]
Is there already a update on this?. 
The jira issue mentions a fix version of 1.4.12, but with that version the message still isn't formatted.

I would love to have both the non formatted and formatted message.

**Comment by ceki** [comment]
Commit 9078f68f49673d2163ebbaa075e enables output of _formattedMessage_  json member. Also all top-level members can enabled/disabled separately.

**Comment by ceki** [comment]
See also documentation of [JsonEncoder ](https://logback.qos.ch/manual/encoders.html#JsonEncoder)

**Comment by lbueker** [comment]
The field was not changed. The message field from the JsonEncoder always was the non interpolated version. Thats why this issue was opened. @leomekenkamp

**Comment by leomekenkamp** [comment]
> The field was not changed. The message field from the JsonEncoder always was the non interpolated version. Thats why this issue was opened. @leomekenkamp

Ah, you are right. I mistook the behaviour of another internal system for the behaviour of the JsonEncoder. My bad, sorry for that.
