### ISSUE TITLE
Some file are licensed only under the LGPL v2.1 only

### ISSUE THREAD

**Issue by rahulmohang** [qos-ch/logback#734]
Hi, 

There are files that are licensed only under the LGPL v2.1 only. This may cause users to use the software under only the LGPL v2.1 only license. The following are the files:

1. https://github.com/qos-ch/logback/blob/master/logback-classic/performance/src/java/ch/qos/logback/classic/pattern/ClassNameAbbreviatorSpeed.java
2. https://github.com/qos-ch/logback/blob/master/logback-core/src/test/input/compress1.copy
3. https://github.com/qos-ch/logback/blob/master/logback-core/src/test/input/compress3.copy
4. https://github.com/qos-ch/logback/blob/master/logback-classic/performance/src/java/ch/qos/logback/classic/LoggerCreation.java
5. https://github.com/qos-ch/logback/blob/master/logback-classic/performance/src/java/ch/qos/logback/classic/RetreivalOfExistingLoggerSpeed.java
6. https://github.com/qos-ch/logback/blob/master/logback-classic/performance/src/java/ch/qos/logback/classic/SpeedOfDisabledDebug.java
7. https://github.com/qos-ch/logback/blob/master/logback-classic/performance/src/java/ch/qos/logback/classic/pattern/WriteSpeed.java

Can you please correct the license text in the files to reflect the dual license that applies to the rest of the source code files?

**Comment by rPraml** [comment]
On the first look, I would say, these files are for test cases not part of the release, so using the release should be safe.
(Nevertheless, the logback guys should take a look at this)

**Comment by GetAHut** [comment]
So is there a way to get rid of the LGPL part of the code? Or has it been removed in the new version, is there a version limit?

**Comment by ceki** [comment]
@rahulmohang The files you mention are not part of the distributed binary. 

In any case, the issue has been fixed in commit f3efb8f166d65a39

**Comment by rahulmohang** [comment]
> @rahulmohang The files you mention are not part of the distributed binary.
> 
> In any case, the issue has been fixed in commit [f3efb8f](https://github.com/qos-ch/logback/commit/f3efb8f166d65a3914f6b5193446c5e4c26ac5ba)

Thank you
