### ISSUE TITLE
Incorrect tag for release 1.4.12

### ISSUE THREAD

**Issue by Stephan202** [qos-ch/logback#740]
Thanks for maintaining this great software! Just dropping by to share the observation that the most recent release was tagged as [4.1.12](https://github.com/qos-ch/logback/releases/tag/v_4.1.12) rather than [1.4.12](https://github.com/qos-ch/logback/releases/tag/v_1.4.12): the _major_ and _minor_ version components are swapped.

**Comment by ceki** [comment]
Thank you! Issue issue be fixed now.
