### ISSUE TITLE
logback-classic 1.5.5 breaks conditional logger from included xml

### ISSUE THREAD

**Issue by johanmast** [qos-ch/logback#805]
After updating to logback-classic 1.5.5, conditional `logger` elements from included files break.

The conditional `logger` is ignored and the following line is logged:

```
WARN in ch.qos.logback.core.model.processor.ImplicitModelHandler - Ignoring unknown property [logger] in [ch.qos.logback.classic.LoggerContext]
```

## Reproduction

logback.xml:
```xml
<configuration>
    <include resource="logback-include.xml"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="STDOUT"/>
    </root>

</configuration>
```

logback-include.xml:
```xml
<included>
    <appender name="file" class="ch.qos.logback.core.FileAppender">
        <file>filelogging.log</file>
        <append>true</append>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <if condition='true'>
        <then>
            <logger name="custom" additivity="false" level="info">
                <appender-ref ref="file"/>
            </logger>
        </then>
    </if>
</included>
```

## Expected behaviour: 

```java
LoggerFactory.getLogger("root").info("test1"); //logged to console
LoggerFactory.getLogger("custom").info("test2"); //logged to file
```

## Actual behaviour: 

```java
LoggerFactory.getLogger("root").info("test1"); //logged to console
LoggerFactory.getLogger("custom").info("test2"); //logged to console
```

The expected behaviour still works with version 1.5.4.

**Comment by fupgang** [comment]
We also recognized broken logging configurations after upgrading logback from 1.5.4 to 1.5.5.
In our case there are `<springProperty>` tags in an included Snippet that are not handled correctly anymore.

Version 1.5.5 migrated `IncludeAction` to `IncludeModelHandler` (af92be47a940393e11decab0a7ee4cb802d2b5e8) , which seems to break something.

**Comment by ceki** [comment]
@fupgang File inclusion code moved from IncludeAction to IncludeModelHandler. This changes the moment file inclusion occurs. 

`<springProperty>` might rely on some logback internals in IncludeAction which have changed. This a different issue than what @johanmast reports above. 

@fupgang Please create a separate issue.

**Comment by ceki** [comment]
@johanmast I will add a test case for the situation you describe which is a very special case, i.e a conditional within an inclusion...

I am correct to assume that you are also using logback-core 1.5.5?

**Comment by johanmast** [comment]
Hi @ceki,

Thank you. Yes, dependencies used are:
- logback-classic 1.5.5
- logback-core 1.5.5
- janino 3.1.12
- slf4j-api 2.0.13

**Comment by ceki** [comment]
Created https://jira.qos.ch/browse/LOGBACK-1768 for tracking.

**Comment by ceki** [comment]
Fixed in commit 759fc25ee38435

**Comment by ceki** [comment]
logback version 1.5.6 was released earlier today.

**Comment by johanmast** [comment]
Thank you @ceki, I can confirm that it works again when using version 1.5.6
