### ISSUE TITLE
Mask or remove specific words from log line

### ISSUE THREAD

**Issue by router19** [qos-ch/logback#828]
Hi
I have a requirement wherein I would want to match a specific regex and dont allow words matching such regex to be logged.

I explored logback matcher but it removed the complete formated message. I need only a specific word matching regex  in the formatted message to be removed or replaced with some characters say *

Example

Formatted message :
I love logback library as it is best. 

Ouput I want if logback matches the regex :
I love library as it is best 
Or
I love ******* library as it is best

**Comment by ceki** [comment]
Hi Vinit, 

Logback comes with the[repalce pattern]( https://logback.qos.ch/manual/layouts.html#replace) which corresponds to your requirements.

**Comment by router19** [comment]
Thank you for your response. Will that impact performance of the
application as each log line will be matched against the regex.

**Comment by ceki** [comment]
Added [LOGBACK-1770](https://jira.qos.ch/browse/LOGBACK-1770) for tracking this issue.

**Comment by ceki** [comment]
Fixed in commit e7d945906d3b156 which introduces MaskedKeyValuePairConverter.
