### ISSUE TITLE
SpringBoot3，JDK17 使用logback配置了<configuration debug="false">依然会打印logback内部日志

### ISSUE THREAD

**Issue by xazhaox** [qos-ch/logback#833]
11:24:30,207 |-INFO in ch.qos.logback.classic.LoggerContext[client_chat_log] - This is logback-classic version 1.4.14
11:24:30,211 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - Here is a list of configurators discovered as a service, by rank: 
11:24:30,211 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 -   org.springframework.boot.logging.logback.RootLogLevelConfigurator
11:24:30,211 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - They will be invoked in order until ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY is returned.
11:24:30,211 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - Constructed configurator of type class org.springframework.boot.logging.logback.RootLogLevelConfigurator
11:24:30,217 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - org.springframework.boot.logging.logback.RootLogLevelConfigurator.configure() call lasted 1 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
11:24:30,217 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
11:24:30,218 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
11:24:30,219 |-INFO in ch.qos.logback.classic.LoggerContext[client_chat_log] - Could NOT find resource [logback-test.scmo]
11:24:30,220 |-INFO in ch.qos.logback.classic.LoggerContext[client_chat_log] - Could NOT find resource [logback.scmo]
11:24:30,220 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 2 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
11:24:30,220 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
11:24:30,220 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
11:24:30,221 |-INFO in ch.qos.logback.classic.LoggerContext[client_chat_log] - Could NOT find resource [logback-test.xml]
11:24:30,222 |-INFO in ch.qos.logback.classic.LoggerContext[client_chat_log] - Could NOT find resource [logback.xml]
11:24:30,222 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 2 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
11:24:30,222 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - Trying to configure with ch.qos.logback.classic.BasicConfigurator
11:24:30,223 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - Constructed configurator of type class ch.qos.logback.classic.BasicConfigurator
11:24:30,223 |-INFO in ch.qos.logback.classic.BasicConfigurator@5217f3d0 - Setting up default configuration.
11:24:30,253 |-INFO in ch.qos.logback.classic.util.ContextInitializer@32232e55 - ch.qos.logback.classic.BasicConfigurator.configure() call lasted 30 milliseconds. ExecutionStatus=NEUTRAL
11:24:30,920 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - Registering a new ReconfigureOnChangeTask ReconfigureOnChangeTask(born:1721100270919)
11:24:30,920 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - Will scan for changes in [file:/E:/workspace/release/openai-ai/client-chat/target/classes/logback-prod.xml] 
11:24:30,921 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - Setting ReconfigureOnChangeTask scanning period to 10 seconds
11:24:30,928 |-INFO in ch.qos.logback.classic.model.processor.ContextNameModelHandler - Setting logger context name as [client_chat_log]
11:24:30,932 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE_LOG]
11:24:30,932 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:24:30,939 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:24:30,957 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [ALL_LOG_FILE]
11:24:30,957 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:24:30,960 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:24:30,973 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@938199512 - Will use gz compression
11:24:30,974 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@938199512 - Will use the pattern logs/client-chat/%d{yyyy-MM-dd}/service_log-%d{yyyy-MM-dd}-%i.log for the active file
11:24:30,996 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@293bb8a5 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/client-chat/%d{yyyy-MM-dd}/service_log-%d{yyyy-MM-dd}-%i.log.gz'.
11:24:30,996 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@293bb8a5 - Roll-over at midnight.
11:24:31,003 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@293bb8a5 - Setting initial period to 2024-07-16T03:24:23.328Z
11:24:31,004 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@293bb8a5 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
11:24:31,004 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@293bb8a5 - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
11:24:31,006 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ALL_LOG_FILE] - Active log file name: logs/client-chat/service_log.log
11:24:31,006 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ALL_LOG_FILE] - File property is set to [logs/client-chat/service_log.log]
11:24:31,008 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [DEBUG_LOG_FILE]
11:24:31,008 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:24:31,008 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:24:31,009 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@37841489 - Will use gz compression
11:24:31,009 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@37841489 - Will use the pattern logs/client-chat/%d{yyyy-MM-dd}/debug_log-%d{yyyy-MM-dd}-%i.log for the active file
11:24:31,009 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6fa590ba - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/client-chat/%d{yyyy-MM-dd}/debug_log-%d{yyyy-MM-dd}-%i.log.gz'.
11:24:31,009 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6fa590ba - Roll-over at midnight.
11:24:31,010 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6fa590ba - Setting initial period to 2024-07-16T03:19:46.149Z
11:24:31,010 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6fa590ba - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
11:24:31,010 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6fa590ba - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
11:24:31,012 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[DEBUG_LOG_FILE] - Active log file name: logs/client-chat/debug_log.log
11:24:31,012 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[DEBUG_LOG_FILE] - File property is set to [logs/client-chat/debug_log.log]
11:24:31,012 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [INFO_LOG_FILE]
11:24:31,012 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:24:31,012 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:24:31,013 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@115945887 - Will use gz compression
11:24:31,014 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@115945887 - Will use the pattern logs/client-chat/%d{yyyy-MM-dd}/info_log-%d{yyyy-MM-dd}-%i.log for the active file
11:24:31,014 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@72e34f77 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/client-chat/%d{yyyy-MM-dd}/info_log-%d{yyyy-MM-dd}-%i.log.gz'.
11:24:31,014 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@72e34f77 - Roll-over at midnight.
11:24:31,015 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@72e34f77 - Setting initial period to 2024-07-16T03:24:23.328Z
11:24:31,015 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@72e34f77 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
11:24:31,015 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@72e34f77 - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
11:24:31,016 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[INFO_LOG_FILE] - Active log file name: logs/client-chat/info_log.log
11:24:31,016 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[INFO_LOG_FILE] - File property is set to [logs/client-chat/info_log.log]
11:24:31,017 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [WARN_LOG_FILE]
11:24:31,017 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:24:31,017 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:24:31,018 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2079961240 - Will use gz compression
11:24:31,019 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2079961240 - Will use the pattern logs/client-chat/%d{yyyy-MM-dd}/warn_log-%d{yyyy-MM-dd}-%i.log for the active file
11:24:31,019 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@389adf1d - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/client-chat/%d{yyyy-MM-dd}/warn_log-%d{yyyy-MM-dd}-%i.log.gz'.
11:24:31,019 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@389adf1d - Roll-over at midnight.
11:24:31,020 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@389adf1d - Setting initial period to 2024-07-16T03:19:48.591Z
11:24:31,020 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@389adf1d - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
11:24:31,020 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@389adf1d - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
11:24:31,021 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[WARN_LOG_FILE] - Active log file name: logs/client-chat/warn_log.log
11:24:31,021 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[WARN_LOG_FILE] - File property is set to [logs/client-chat/warn_log.log]
11:24:31,021 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [ERROR_LOG_FILE]
11:24:31,021 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:24:31,022 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:24:31,023 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1999664216 - Will use gz compression
11:24:31,023 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1999664216 - Will use the pattern logs/client-chat/%d{yyyy-MM-dd}/error_log-%d{yyyy-MM-dd}-%i.log for the active file
11:24:31,023 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1fc0053e - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/client-chat/%d{yyyy-MM-dd}/error_log-%d{yyyy-MM-dd}-%i.log.gz'.
11:24:31,023 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1fc0053e - Roll-over at midnight.
11:24:31,024 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1fc0053e - Setting initial period to 2024-07-16T02:17:46.140Z
11:24:31,024 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1fc0053e - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
11:24:31,024 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1fc0053e - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
11:24:31,025 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_LOG_FILE] - Active log file name: logs/client-chat/error_log.log
11:24:31,025 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_LOG_FILE] - File property is set to [logs/client-chat/error_log.log]
11:24:31,026 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.xazhao] to DEBUG
11:24:31,026 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@290b1b2e - Propagating DEBUG level on Logger[com.xazhao] onto the JUL framework
11:24:31,028 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.xazhao] to true
11:24:31,028 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
11:24:31,028 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@290b1b2e - Propagating INFO level on Logger[ROOT] onto the JUL framework
11:24:31,028 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE_LOG] to Logger[ROOT]
11:24:31,028 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [ALL_LOG_FILE] to Logger[ROOT]
11:24:31,028 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [DEBUG_LOG_FILE] to Logger[ROOT]
11:24:31,028 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [INFO_LOG_FILE] to Logger[ROOT]
11:24:31,028 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [WARN_LOG_FILE] to Logger[ROOT]
11:24:31,028 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [ERROR_LOG_FILE] to Logger[ROOT]
11:24:31,028 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@47874b25 - End of configuration.
11:24:31,028 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@33617539 - Registering current configuration as safe fallback point

**Comment by ceki** [comment]
This report lacks information and is generally unclear. Closing.
