### ISSUE TITLE
log file not getting generated after migrating to java 17

### ISSUE THREAD

**Issue by ravadisagarrao** [qos-ch/logback#852]
After upgraded our application from java 8 to Java 17 log file is not getting generated with logback version 1.3.14

When searched in google found that 1.3.14 supports till Java 8, so added latest logback version 1.5.7 in pom.xml but still log file is not getting generated.

Could someone please review below logback.xml config file and let me know whether am I missing something?
`<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">

    <contextName>cmd-cxp-api</contextName>
    <jmxConfigurator />
<property file="${config.file.location}" />
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %X{tenant.id} %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${log.file.location}/emcd_server.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            
            <fileNamePattern>${log.file.location}/emcd_server.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                
                <maxFileSize>10MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
            
            <maxHistory>30</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>%date %level %X{tenant.id} [%thread] %logger{10} [%file:%line] %msg%n</pattern>
        </encoder>
    </appender>

    <logger name="com.xxx.mobile">
        <level value="TRACE" />
    </logger>

    <logger name="org.springframework">
        <level value="TRACE" />
    </logger>

    <logger name="org.apache">
        <level value="TRACE" />
    </logger>

    <root level="WARN">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="FILE" />
    </root>

</configuration>`

**Comment by ceki** [comment]
@ravadisagarrao  Please add a status listener as shown below and report back the results here.
```
<configuration attributes_if_any...>
   <!-- Recommendation: place status listeners towards the the top of the configuration file -->
   <statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />

   <!-- ... the rest of the configuration file -->

</configuration>```

**Comment by ravadisagarrao** [comment]
@ceki , tried above status listener but still not able to generate log file.

**Comment by ceki** [comment]
@ravadisagarrao  Can you include the resulting status output?

**Comment by ravadisagarrao** [comment]
Verified in Tomee startup logs, status output is not found. Do let me know if you need any more info.

**Comment by ceki** [comment]
@ravadisagarrao It looks like your logback.xml configuration file  is not picked up at all. 

Adding the  ["logback.statusListenerClass" system property](https://logback.qos.ch/manual/configuration.html#logback.statusLC) with "java -Dlogback.statusListenerClass=stdout" might help see the status messages.

However, this assumes that slf4j finds logback. **Are you using slf4j and if so which version?**

**Comment by ravadisagarrao** [comment]
@ceki, I have set as below in setenv.bat file.

set CATALINA_OPTS=%CATALINA_OPTS% "-Dpassport.properties.dir.cmd=C:\emcd"
**set java "-Dlogback.statusListenerClass=stdout"**

 is this correct? If yes still not seeing status messages. If NO could you please let me know how and where can i add it.

And **I am using slf4j version:2.0.13**

**Comment by ceki** [comment]
Try 

```set CATALINA_OPTS=%CATALINA_OPTS% "-Dlogback.statusListenerClass=stdout -Dpassport.properties.dir.cmd=C:\emcd"```

Also, what is the output of SLF4J?

I suggest upgrading to slf4j version 2.0.16 and adding the following to CATALINA_OPTS

```-Dslf4j.internal.verbosity=DEBUG```

**Comment by ravadisagarrao** [comment]
1. Yes added system properties as suggested.
2. Searched with SLF4J but nothing found but when I removed slf4j jar from tomee lib folder it complained below in logs.
    **"SLF4J: No SLF4J providers were found."** and after adding slf4j jar this error is gone.
3. Also upgraded to slf4j version 2.0.16 and added set CATALINA_OPTS=%CATALINA_OPTS% "-Dslf4j.internal.verbosity=DEBUG"
   and still no luck.
FYI, please find the tomee startup log file attached.
[catalina.2024-08-27.log](https://github.com/user-attachments/files/16761991/catalina.2024-08-27.log)

**Comment by ceki** [comment]
Are you trying to use slf4j/logback for TomEE or for web-application's logging? Where are  you placing slf4j and logback jar files? Is it in your application's EAR/WAR file or in TomEE's lib folder? 

Also if you are using slf4j 2.0.16 I recommend using the latest logback version.

**Comment by ravadisagarrao** [comment]
We are using logback for web app's logging. We placed logback jar files inside WAR file and SLF4j-api is placed in both WAR and Tomee lib folder.
Yes using slf4j 2.0.16, I am already on logback latest version 1.5.7

**Comment by ravadisagarrao** [comment]
Finally, its working now. After freshly checking out code and rebuilt with upgraded dependencies able to generate loggers.

Thanks for your time in troubleshooting. :)

**Comment by AdamUlatowski** [comment]
Why this Issue is still open?
