### ISSUE TITLE
Change in LoggerContext.getConfigurationLock causes NoSuchMethodError in Spring Boot

### ISSUE THREAD

**Issue by fcpunk** [qos-ch/logback#853]
Hi,

This issue is related to the change that was made here: https://github.com/qos-ch/logback/issues/844 in commit https://github.com/qos-ch/logback-access/commit/b5096c5090bb5936

Spring Boot expects getConfigurationLock to return an Object and fails with NoSuchMethodError.

Caused by: java.lang.NoSuchMethodError: ‘java.lang.Object ch.qos.logback.classic.LoggerContext.getConfigurationLock()’
at org.springframework.boot.logging.logback.LogbackConfigurator.getConfigurationLock(LogbackConfigurator.java:53)

Affected logback version: 1.5.7
Latest logback version that works properly: 1.5.6
Tested on Boot version: 3.1.12

**Comment by ceki** [comment]
@fcpunk Spring boot has updated their code in [commit dd2ed5f1]( https://github.com/spring-projects/spring-boot/commit/dd2ed5f12d23b15ff0055e366ab6da8e95218596)

I am marking this issue as closed,

**Comment by arvindkrishnakumar-okta** [comment]
This is still an issue with 1.5.8 and needs to be fixed.
