### ISSUE TITLE
Unable to Disable "SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]"

### ISSUE THREAD

**Issue by barrownicholas** [qos-ch/logback#872]
https://github.com/qos-ch/logback/blob/df2a3b6e7dca7e3a3835a123f6e1b07909bd79f6/logback-classic/src/test/java/ch/qos/logback/classic/spi/InvocationTest.java#L23

^ this line is showing up in my logs, and cannot be disabled. It does not exist in 1.5.6, and seems to have been introduced in 1.5.7. I am writing a CLI, so I don't want this shown... is there a way to prevent this from always spitting out into the console?

**Comment by ceki** [comment]
@barrownicholas  The line in question starts with "SLF4J(I): Connected with provider". As the SLF4J prefix of the message suggests, the message is emitted by slf4j-api and not logback-classic. The invocation test cited above checks that the message is indeed emitted to verify that logback-classic can connect with SLF4J. 

The message can be suppressed by setting the "slf4j.internal.verbosity" system property to WARN. See also 

See also the FAQ entry ["Is there a way to control the internal messages emitted by SLF4J?"](https://www.slf4j.org/faq.html#internalMessages)

Please report back whether the above solution worked for you.

**Comment by barrownicholas** [comment]
@ceki I'll give that a shot, thanks! I'll close this out and just re-open if I can't suppress it and can trace it back to logback instead of slf4j.
