### ISSUE TITLE
logback-tyler sometimes produces Java Code that still relies on XML Parsers and Janino

### ISSUE THREAD

**Issue by DarkAtra** [qos-ch/logback#873]
The logback-tyler readme claims that:
> Running TylerConfigurator does not require XML parsers and usually executes noticeably faster than JoranConfigurator, logback's XML configurator.

However, `<include resource="logback-console-appender.xml"/>` is translated to:
```java
IncludeModel includeModel = new IncludeModel();
includeModel.setResource(subst("logback-console-appender.xml"));
IncludeModelHandler includeModelHandler = new IncludeModelHandler(context);
try {
    Model modelFromIncludedFile = includeModelHandler.buildModelFromIncludedFile(this, includeModel);
    processModelFromIncludedFile(modelFromIncludedFile);
} catch(ModelHandlerException e) {
    addError("Failed to process IncludeModelHandler", e);
}
```
To me it seems like `includeModelHandler.buildModelFromIncludedFile(this, includeModel)` uses an XML parser internally and the referenced xml file is probably also allowed to use conditions which then also requires Janino (an issue with GraalMV).

Is there any way to configure logback-tyler so that it also resolves and translates included files?

Versions:
```
logback-classic: 1.5.11
logback-tyler: 0.9
```

**Comment by ceki** [comment]
@DarkAtra Thank you for this report.

I have [modified ](https://github.com/qos-ch/logback-tyler/commit/cde313de7c17df027b811b8e5f338fe1db1a7a16)the generated code to have an `include()` method the contents of which are very similar to the code you mention above. 

Please note at translation time logback-tyler usually does not have access to the included file.
        
It follows that the code in `include()` method produced by logback-tyler falls back to invoking  logback-classic's default configurator, i.e. JoranConfigurator which will invoke an XML  parser in the process.
       
If you wish to avoid calling JoranConfigurator, then you can insert the contents of the  included XML file into the containing file manually before performing the logback-tyler translation.
        
Also note that `PropertiesConfigurator` introduced in version 1.5.8, allows for setting logger levels via a properties file. The location of properties files can be specified as a file path as well a URL via HTTP or HTTPS protocols. Watching files and reconfiguration upon change is also supported. Logback-tyler supports PropertiesConfigurator.

**Comment by DarkAtra** [comment]
Ok, i just wanted to make sure that this is expected behaviour. I will merge our XML configs and run them through logback-tyler again
