### ISSUE TITLE
Please push 1.5.13 tag

### ISSUE THREAD

**Issue by pzygielo** [qos-ch/logback#886]

**Comment by pzygielo** [comment]
I'm probably sorry :grin: for the noise.

Thought it was some bit older release, but it is just hours old.

**Comment by ceki** [comment]
@pzygielo Thank  you for the reminder. Tagged commit  32638aa7e99c0135cb1b81806ed05352e6bfe27f

**Comment by pzygielo** [comment]
Thank you.
